<a href="https://colab.research.google.com/github/embark-cybertraining/embark-scratch-notebooks/blob/main/obis_filter_by_areaid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Query OBIS for one species in one marine region and display summary information and map locations.

This notebook was constructed with the goal of porting functionality from an r script using "robis" OBIS_filter_by_areaid.R to python using "pyobis".

Strategy was revised to do an obis api call directly instead of through the pythong client pyobis in order to use the areaid param instead of passing an area geometry which would be required to use pyobis.

OBIS API https://api.obis.org/
pyobis https://iobis.github.io/pyobis/

ChatGPT5.3 was utilized to help port the functionality with oversight, editing for purpose, and review by the embark project participants.

In [24]:
"""
Query OBIS for one species in one marine region and display summary information.

Purpose:
- Retrieve OBIS occurrence records for a scientific name within an areaid
- Display summary information
- Map locations of the occurrence records for data exploration

Usage:
- Edit SCIENTIFIC_NAME AREA_NAME, and AREA_ID as needed

"""

import requests
import folium
from datetime import datetime
import pandas as pd
from IPython.display import display

SCIENTIFIC_NAME = "Pyrosoma atlanticum"
AREA_ID = 40003
AREA_NAME = 'California Current'
RECORD_LIMIT = 10000 #query up to this many records

#Query up to 10k records in one call
def fetch_obis_occurrences(scientific_name, area_id, size):
    r = requests.get(
        "https://api.obis.org/v3/occurrence",
        params={
            "scientificname": scientific_name,
            "areaid": area_id,
            "size": size,
        },
        timeout=60,
    )
    r.raise_for_status() #raises an exception if the request failed
    return pd.DataFrame(r.json().get("results", []))

records = fetch_obis_occurrences(SCIENTIFIC_NAME, AREA_ID, RECORD_LIMIT)

## show summary info
print(f"Scientific name: {SCIENTIFIC_NAME}")
print(f"Area ID: {AREA_ID}")
print(f"Total records retrieved: {len(records)}")
if len(records) <= RECORD_LIMIT:
    print("All records retrieved.")

Scientific name: Pyrosoma atlanticum
Area ID: 40003
Total records retrieved: 483
All records retrieved.

In [4]:
# If you want to save as a csv file:

output_file = "obis_occurrences_pyrosoma_atlanticum_california_current.csv"
records.to_csv(output_file, index=False)
print(f"Saved to: {output_file}")

Saved to: obis_occurrences_pyrosoma_atlanticum_california_current.csv

In [18]:
#More summary info

if records.empty:
    print("No records returned.")
else:
    print("\nColumns returned:")
    print(sorted(records.columns.tolist()))

    # Optional preview of key fields
    preview_cols = [
        "scientificName",
        "decimalLatitude",
        "decimalLongitude",
        "eventDate",
        "minimumDepthInMeters",
        "maximumDepthInMeters",
        "occurrenceStatus",
        "datasetID",
        "occurrenceID"
    ]

    print("\nPreview of key fields (random 10 lines)")
    display(records[preview_cols].sample(10))

    # Unique aphiaID values with WoRMS links

    aphia_values = pd.Series(records["aphiaID"].dropna().unique(), name="aphiaID")
    aphia_df = pd.DataFrame({"aphiaID": aphia_values})
    aphia_df["WoRMS_link"] = aphia_df["aphiaID"].apply(
        lambda x: f"https://marinespecies.org/aphia.php?p=taxdetails&id={int(x)}"
        if pd.notna(x) else None
    )

    display(aphia_df.sort_values("aphiaID").reset_index(drop=True))

    # Unique datasets, add OBIS links

    records["datasetURL"] = 'https://obis.org/dataset/'+ records['dataset_id'].astype(str)

    # Extract unique combinations
    datasets = (
        records[['dataset_id',"datasetName",'datasetID','datasetURL']]
        .drop_duplicates()
        .sort_values(by="datasetName")
        .reset_index(drop=True)
    )

    print(f"\nTotal unique datasets: {len(datasets)}")
    display(datasets)

Columns returned:
['absence', 'aphiaID', 'basisOfRecord', 'bathymetry', 'class', 'classid', 'country', 'datasetID', 'datasetName', 'dataset_id', 'date_end', 'date_mid', 'date_start', 'date_year', 'decimalLatitude', 'decimalLongitude', 'depth', 'dropped', 'eventDate', 'eventID', 'eventRemarks', 'eventTime', 'family', 'familyid', 'flags', 'genus', 'genusid', 'geodeticDatum', 'higherClassification', 'id', 'identificationRemarks', 'individualCount', 'institutionID', 'kingdom', 'kingdomid', 'language', 'license', 'lifeStage', 'locality', 'locationID', 'locationRemarks', 'marine', 'materialSampleID', 'maximumDepthInMeters', 'maximumElevationInMeters', 'minimumDepthInMeters', 'minimumElevationInMeters', 'modified', 'node_id', 'occurrenceID', 'occurrenceStatus', 'order', 'orderid', 'organismQuantity', 'organismQuantityType', 'originalScientificName', 'ownerInstitutionCode', 'parentEventID', 'phylum', 'phylumid', 'recordedBy', 'references', 'sampleSizeUnit', 'sampleSizeValue', 'samplingEffort', 'samplingProtocol', 'scientificName', 'scientificNameID', 'shoredistance', 'species', 'speciesid', 'sss', 'sst', 'stateProvince', 'subfamily', 'subfamilyid', 'subphylum', 'subphylumid', 'taxonRank', 'taxonRemarks', 'taxonomicStatus', 'type', 'verbatimDepth', 'verbatimIdentification', 'verbatimLocality', 'vernacularName', 'waterBody']

Preview of key fields (random 10 lines)

,scientificName,decimalLatitude,decimalLongitude,eventDate,minimumDepthInMeters,maximumDepthInMeters,occurrenceStatus,datasetID,occurrenceID
2,Pyrosoma atlanticum,35.705200,-121.507200,2014-05-30T07:29:06Z,25.000000,30.000000,present,RockfishRecruitmentAndEcosystemAssessmentSurve...,98fecfcb-a925-43d2-9215-50881485c7c8
1,Pyrosoma atlanticum,36.744500,-121.977000,2012-05-31T07:49:21Z,25.000000,30.000000,present,RockfishRecruitmentAndEcosystemAssessmentSurve...,eb38cddf-cc12-4bdf-9388-3629930b20e2
8,Pyrosoma atlanticum,36.979300,-122.289200,2012-06-11T04:40:56Z,25.000000,30.000000,present,RockfishRecruitmentAndEcosystemAssessmentSurve...,6becb1ba-3107-498f-a660-7cb836f9f8ec
5,Pyrosoma atlanticum,33.379800,-119.773300,2013-06-09T04:01:14Z,25.000000,30.000000,present,RockfishRecruitmentAndEcosystemAssessmentSurve...,8dfbb85e-5670-437d-b3f8-864ae46a7c31
9,Pyrosoma atlanticum,36.983200,-122.427200,2013-05-28T07:53:35Z,25.000000,30.000000,present,RockfishRecruitmentAndEcosystemAssessmentSurve...,1dcb4223-1723-4301-b1ac-0d5dcb7630fc
6,Pyrosoma atlanticum,35.000700,-120.888800,2012-05-29T06:00:20Z,25.000000,30.000000,present,RockfishRecruitmentAndEcosystemAssessmentSurve...,3be360a4-f0b0-451c-8edc-a03d012ecb4d
0,Pyrosoma atlanticum,41.494953,-125.095577,2023-04-20T22:07:39Z,2316.368896,2316.368896,present,noaa-oer-okeanos-ex2301,noaa-oer-okeanos-ex2301:OKEX2301_ROV-D2_18S_na...
3,Pyrosoma atlanticum,35.709500,-121.507800,2012-05-30T07:28:18Z,25.000000,30.000000,present,RockfishRecruitmentAndEcosystemAssessmentSurve...,b0be9481-183e-437a-a178-1110c50d3e14
4,Pyrosoma atlanticum,40.500500,-124.617700,2014-06-14T06:16:14Z,25.000000,30.000000,present,RockfishRecruitmentAndEcosystemAssessmentSurve...,604fa7ea-138e-4b9f-ae31-e00802f6a40c
7,Pyrosoma atlanticum,36.300700,-122.012700,2014-06-01T05:31:09Z,25.000000,30.000000,present,RockfishRecruitmentAndEcosystemAssessmentSurve...,2e152bbe-2b3a-4092-b58c-9b93956b822b

   aphiaID                                         WoRMS_link
0   137250  https://marinespecies.org/aphia.php?p=taxdetai...

Total unique datasets: 2

,dataset_id,datasetName,datasetID,datasetURL
0,5b6251f6-a7a5-4dc9-994d-c9504b54776f,Rockfish Recruitment and Ecosystem Assessment ...,RockfishRecruitmentAndEcosystemAssessmentSurve...,https://obis.org/dataset/5b6251f6-a7a5-4dc9-99...
1,71c2c816-7e94-40b9-8e28-8172d9c5fefb,NaN,noaa-oer-okeanos-ex2301,https://obis.org/dataset/71c2c816-7e94-40b9-8e...

In [6]:
# Plot OBIS occurrence records from the `records` DataFrame

def plot_obis_records(records_df):
    """
    Return a folium map of OBIS occurrence points.
    """
    required = {"decimalLatitude", "decimalLongitude"}
    missing = required - set(records_df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    df = records_df.dropna(subset=list(required))
    if df.empty:
        raise ValueError("No valid coordinate rows.")

    m = folium.Map(
        location=[df["decimalLatitude"].mean(), df["decimalLongitude"].mean()],
        zoom_start=4
    )

    #add this info in a popup using html table
    preview_cols = ["scientificName","decimalLatitude","decimalLongitude",
                    "eventDate","minimumDepthInMeters","maximumDepthInMeters","occurrenceID" ]

    cols = [c for c in preview_cols if c in df.columns]

    for _, r in df.iterrows():
        rows = [
            f"<tr><th>{c}</th><td>{r[c]}</td></tr>"
            for c in cols if pd.notna(r.get(c))
        ]

        popup = folium.Popup(f"<table>{''.join(rows)}</table>", max_width=300)

        folium.CircleMarker(
            location=[r.decimalLatitude, r.decimalLongitude],
            radius=3,
            weight=1,
            fill=True,
            popup=popup,
        ).add_to(m)

    return m

obis_map = plot_obis_records(records)
obis_map

# Source Datasets and Metadata

Dataset info pattern
https://obis.org/dataset/5b6251f6-a7a5-4dc9-994d-c9504b54776f
* You can see "Overview" and "Data Quality" sections which include information about quality flags, missing data identifiers, coordinate precision, etc.

You can get the unique set of dataset_id column in records to look at metadata for any information you need about the source datasets in obis.

In [7]:
# We alread got the unique list of datasets from records
datasets

,dataset_id,datasetName,datasetID,datasetURL
0,5b6251f6-a7a5-4dc9-994d-c9504b54776f,Rockfish Recruitment and Ecosystem Assessment ...,RockfishRecruitmentAndEcosystemAssessmentSurve...,https://obis.org/dataset/5b6251f6-a7a5-4dc9-99...
1,71c2c816-7e94-40b9-8e28-8172d9c5fefb,NaN,noaa-oer-okeanos-ex2301,https://obis.org/dataset/71c2c816-7e94-40b9-8e...
2,c5687a17-e454-40f9-9a4b-d04b2c812d74,NaN,NaN,https://obis.org/dataset/c5687a17-e454-40f9-9a...
3,aa16d305-d413-4c4a-90be-b1ec3298d58d,NaN,NaN,https://obis.org/dataset/aa16d305-d413-4c4a-90...

In [8]:
#You can visit the links for more info about the dataset
datasets["datasetURL"].dropna().tolist()

['https://obis.org/dataset/5b6251f6-a7a5-4dc9-994d-c9504b54776f',
 'https://obis.org/dataset/71c2c816-7e94-40b9-8e28-8172d9c5fefb',
 'https://obis.org/dataset/c5687a17-e454-40f9-9a4b-d04b2c812d74',
 'https://obis.org/dataset/aa16d305-d413-4c4a-90be-b1ec3298d58d']

In [9]:
# Dataset citation for OBIS
# * Citation based on https://manual.obis.org/citing.html

#citaion builder based on this script's variables
now = datetime.now()
year = now.year
access_date = now.strftime("%B %d, %Y")

citation = (
    f"Ocean Biodiversity Information System (OBIS). ({year}). "
    f"Occurrence records of {SCIENTIFIC_NAME} in the {AREA_NAME} (LME {AREA_ID}). "
    f"https://obis.org (accessed {access_date})."
)

print("OBIS citation:\n")
print(citation)

OBIS citation:

Ocean Biodiversity Information System (OBIS). (2026). Occurrence records of Pyrosoma atlanticum in the California Current (LME 40003). https://obis.org (accessed May 08, 2026).

# Testing same functionality but with pyobis call with a geometry string (not an area id)

In [25]:
!pip install pyobis

Collecting pyobis
  Using cached pyobis-1.6.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: requests>2.7 in /usr/local/lib/python3.12/dist-packages (from pyobis) (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pyobis) (2.2.2)
Collecting requests-cache<2.0.0,>=1.2.0 (from pyobis)
  Using cached requests_cache-1.3.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>2.7->pyobis) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>2.7->pyobis) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>2.7->pyobis) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>2.7->pyobis) (2026.4.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache<2.0.0,>=1.2.0->pyobis) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache<2.0.0,>=1.2.0->pyobis)
  Using cached cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache<2.0.0,>=1.2.0->pyobis) (4.9.6)
Collecting url-normalize>=2.0 (from requests-cache<2.0.0,>=1.2.0->pyobis)
  Using cached url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas->pyobis) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pyobis) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pyobis) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pyobis) (2026.1)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache<2.0.0,>=1.2.0->pyobis) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pyobis) (1.17.0)
Using cached pyobis-1.6.1-py3-none-any.whl (29 kB)
Using cached requests_cache-1.3.1-py3-none-any.whl (70 kB)
Using cached cattrs-26.1.0-py3-none-any.whl (73 kB)
Using cached url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, pyobis
Successfully installed cattrs-26.1.0 pyobis-1.6.1 requests-cache-1.3.1 url-normalize-3.0.0

In [34]:
#investigating this region to see the info about it before using the geometry string

import requests
import pandas as pd

MRGID = 8549  # California Current (Marine Regions)

url = f"https://www.marineregions.org/rest/getGazetteerRecordByMRGID.json/{MRGID}/"
r = requests.get(url, timeout=60)
r.raise_for_status()

data = r.json()

# Flatten key fields for easy viewing
info = {
    "MRGID": data.get("MRGID"),
    "preferred_name": data.get("preferredGazetteerName"),
    "place_type": data.get("placeType"),
    "status": data.get("status"),
    "latitude": data.get("latitude"),
    "longitude": data.get("longitude"),
}

df = pd.DataFrame([info])
print(df)

# Full raw record if needed
data

   MRGID      preferred_name              place_type    status  latitude  \
0   8549  California Current  Large Marine Ecosystem  altclass  33.25191

   longitude
0 -122.51089

{'MRGID': 8549,
 'gazetteerSource': 'Large Marine Ecosystems of the World',
 'placeType': 'Large Marine Ecosystem',
 'latitude': 33.25191,
 'longitude': -122.51089,
 'minLatitude': 21.83586,
 'minLongitude': -132.11243,
 'maxLatitude': 47.90313,
 'maxLongitude': -108.75468,
 'precision': 1784230,
 'preferredGazetteerName': 'California Current',
 'preferredGazetteerNameLang': 'English',
 'status': 'altclass',
 'accepted': 8549}

In [61]:
#get the geometry

import re
import requests

MRGID = 8549  # California Current (Marine Regions)

url = f"https://www.marineregions.org/rest/getGazetteerGeometries.jsonld/{MRGID}/"
r = requests.get(url, timeout=60)
r.raise_for_status()

data = r.json()
geometry_wkt = None

for geom in data.get("mr:hasGeometry", []):
    wkt = geom.get("gsp:asWKT")
    if wkt:
        geometry_wkt = re.sub(r"<[^>]+>\s*", "", wkt).strip()
        break

print("Preview the geom")
print(geometry_wkt[0:100])
print("Geometry length="+str(len(geometry_wkt)))

Preview the geom
POLYGON ((-109.91147613 22.8783226, -108.75467682 21.83747101, -108.7578125 21.83586121, -109.616462
Geometry length=108685

In [55]:
#look at a query using example species and geom pybix occurences examples use too to make sure it works
from pyobis import occurrences
import pandas as pd

query = occurrences.search(
    scientificname="Mola mola",
    geometry="POLYGON((30.1 10.1, 10 20, 20 40, 40 40, 30.1 10.1))",
    size=RECORD_LIMIT,
    cache=True
)

query.execute()

df = pd.DataFrame(query.data["results"])

display(df.head())

print(query.api_url)
print(query.mapper_url)

,associatedReferences,basisOfRecord,bibliographicCitation,brackish,catalogNumber,class,classid,collectionCode,coordinatePrecision,datasetID,...,absence,originalScientificName,aphiaID,category,flags,bathymetry,shoredistance,sst,sss,coordinateUncertaintyInMeters
0,"[{""crossref"":{""citeinfo"":{""origin"":""Halpin, P....",HumanObservation,"[{""crossref"":{""citeinfo"":{""origin"":""Halpin, P....",False,2322_22,Teleostei,293496,2322,1e-06,2322,...,False,Mola mola,127405,VU,[NO_DEPTH],4338,32472,20.85,38.22,NaN
1,"[{""crossref"":{""citeinfo"":{""origin"":""Halpin, P....",HumanObservation,"[{""crossref"":{""citeinfo"":{""origin"":""Halpin, P....",False,1158_2698,Teleostei,293496,1158,1e-05,1158,...,False,Mola mola,127405,VU,[NO_DEPTH],248,9219,20.44,38.52,1.11

https://api.obis.org/v3/occurrence?scientificname=Mola+mola&geometry=POLYGON%28%2830.1+10.1%2C+10+20%2C+20+40%2C+40+40%2C+30.1+10.1%29%29&offset=0&mof=False&size=10000
https://mapper.obis.org/?taxonid=127405&scientificname=Mola+mola&geometry=POLYGON%28%2830.1+10.1%2C+10+20%2C+20+40%2C+40+40%2C+30.1+10.1%29%29&offset=0&mof=False&size=10000

In [56]:
#look at a query using example species and geom pybix occurences examples use too. May not be able to get around the url too large calling this way.
from pyobis import occurrences
import pandas as pd

query = occurrences.search(
    scientificname=SCIENTIFIC_NAME,
    geometry=geometry_wkt,
    size=RECORD_LIMIT,
    cache=True
)

query.execute()

df = pd.DataFrame(query.data["results"])

display(df.head())

print(query.api_url)
print(query.mapper_url)

HTTPError: 414 Client Error: Request-URI Too Large for url: https://api.obis.org/v3/occurrence?taxonid=137250&scientificname=Pyrosoma+atlanticum&geometry=POLYGON+%28%28-109.91147613+22.8783226%2C+-108.75467682+21.83747101%2C+-108.7578125+21.83586121%2C+-109.61646271+21.89846611%2C+-110.6988678+21.94595146%2C+-112.19152832+21.9803009%2C+-113.03099823+21.98961067%2C+-113.32858276+21.94040298%2C+-114.03866577+22.0181179%2C+-114.9164505+22.07999802%2C+-115.5743103+22.0719471%2C+-115.68096161+22.07064247%2C+-116.4107666+22.18305588%2C+-117.51317596+22.26417541%2C+-118.03858185+22.39151382%2C+-118.62602234+22.74551201%2C+-119.15538025+22.99394035%2C+-120.02405548+23.33173561%2C+-120.55944061+23.73477936%2C+-120.78397369+24.32380676%2C+-121.20969391+24.74063683%2C+-121.65570068+25.17365837%2C+-122.35441589+25.81252289%2C+-123.31045532+26.70539856%2C+-124.16611481+27.355196%2C+-124.7996521+28.01731682%2C+-125.1881485+28.62464333%2C+-125.60649109+29.39650726%2C+-126.06056976+30.08115196%2C+-126.71607208+30.61394501%2C+-127.37185669+31.40766716%2C+-127.86400604+31.96675301%2C+-128.26676941+32.57195282%2C+-128.69602966+33.49822235%2C+-129.13487244+34.4816246%2C+-129.42042542+35.39329147%2C+-129.9185791+36.48691177%2C+-130.48262024+37.5848999%2C+-131.01394653+38.47000885%2C+-131.24121094+39.16427231%2C+-131.4717865+39.68531799%2C+-131.67924499+40.32566452%2C+-131.69674683+40.81182861%2C+-131.80552673+41.40050507%2C+-132.06085205+42.20876312%2C+-132.03215027+42.59686661%2C+-132.11242676+43.2142334%2C+-131.99198914+43.33878326%2C+-131.13116455+43.93698883%2C+-130.17173767+44.54769897%2C+-129.26301575+44.96548462%2C+-128.47398376+45.40942001%2C+-127.18730164+46.14489365%2C+-126.53325653+46.59677505%2C+-125.8558197+47.03257751%2C+-124.59822845+47.90312576%2C+-124.59249878+47.89387894%2C+-124.59059906+47.88832855%2C+-124.58560181+47.88471985%2C+-124.58209991+47.88374519%2C+-124.57860565+47.88277054%2C+-124.57860023+47.88277115%2C+-124.57859802+47.88277054%2C+-124.56999933+47.88374523%2C+-124.56139641+47.88471955%2C+-124.55220032+47.88415909%2C+-124.54167538+47.87987387%2C+-124.53310394+47.87638092%2C+-124.49889755+47.85138512%2C+-124.46469879+47.82638931%2C+-124.45890045+47.81610107%2C+-124.45580292+47.79748917%2C+-124.43699646+47.76971054%2C+-124.42690277+47.76332855%2C+-124.40579987+47.75638962%2C+-124.39779663+47.74805069%2C+-124.39499664+47.72943115%2C+-124.38500214+47.71554947%2C+-124.37220001+47.68943024%2C+-124.36219788+47.67554855%2C+-124.35639954+47.65887833%2C+-124.35639954+47.652771%2C+-124.35140228+47.63555145%2C+-124.34965373+47.62003678%2C+-124.34780884+47.60359955%2C+-124.33623686+47.57077767%2C+-124.334198+47.564991%2C+-124.33335963+47.56149673%2C+-124.32720947+47.53583527%2C+-124.32080078+47.49805069%2C+-124.3219986+47.47803879%2C+-124.31920624+47.45943451%2C+-124.31330872+47.44276047%2C+-124.30719757+47.43304825%2C+-124.30750275+47.42694092%2C+-124.30249786+47.40970993%2C+-124.30079651+47.37110138%2C+-124.29939643+47.36902034%2C+-124.29800415+47.36693954%2C+-124.29000092+47.36471939%2C+-124.27000427+47.36471939%2C+-124.26190186+47.36333084%2C+-124.25610352+47.36027908%2C+-124.26699829+47.35416031%2C+-124.26809692+47.34804916%2C+-124.26719666+47.34193039%2C+-124.26329804+47.33776855%2C+-124.26029968+47.3260994%2C+-124.25640106+47.32194138%2C+-124.24639893+47.32165909%2C+-124.23139954+47.31832886%2C+-124.22750092+47.31415939%2C+-124.2213974+47.30498886%2C+-124.21579742+47.28860092%2C+-124.20890045+47.27943039%2C+-124.19419861+47.24222183%2C+-124.1832962+47.2213707%2C+-124.18000031+47.18970871%2C+-124.1753006+47.16553879%2C+-124.1588974+47.11444092%2C+-124.15699768+47.10221863%2C+-124.15309906+47.09109879%2C+-124.14859772+47.06082153%2C+-124.14890289+47.03305054%2C+-124.15219879+47.00777054%2C+-124.16419983+46.94638061%2C+-124.16190338+46.94110107%2C+-124.15499878+46.93888092%2C+-124.14920044+46.94166183%2C+-124.14420319+46.94498825%2C+-124.14199066+46.95055008%2C+-124.13188934+46.96416092%2C+-124.1118927+46.97166061%2C+-124.10890198+46.97637939%2C+-124.10970306+46.98276901%2C+-124.12249756+47.00138855%2C+-124.12329864+47.01443863%2C+-124.12220001+47.02054977%2C+-124.12689972+47.03026962%2C+-124.13200378+47.03443909%2C+-124.13500214+47.03944016%2C+-124.13279724+47.0447197%2C+-124.12470245+47.05305099%2C+-124.11360168+47.05915832%2C+-124.1006012+47.06388092%2C+-124.08439636+47.06666946%2C+-124.05780029+47.06415939%2C+-124.04389954+47.05998611%2C+-124.03558786+47.05564383%2C+-124.02690125+47.05110168%2C+-124.01699829+47.04333115%2C+-124.00140381+47.02666092%2C+-123.99749756+47.00860977%2C+-123.99469757+47.00387955%2C+-123.97389984+46.99054718%2C+-123.96691132+46.98860168%2C+-123.96690369+46.98860168%2C+-123.95690155+46.98860168%2C+-123.92690277+46.99526978%2C+-123.9111023+46.99721909%2C+-123.90920258+46.99082947%2C+-123.9117012+46.9894352%2C+-123.91420746+46.98804092%2C+-123.91569892+46.98540512%2C+-123.91719818+46.98276901%2C+-123.82949829+46.98138046%2C+-123.80280304+46.97887039%2C+-123.79669952+46.97610092%2C+-123.87190247+46.95331955%2C+-123.93890381+46.93748856%2C+-123.97190094+46.93276978%2C+-123.97419739+46.9205513%2C+-123.97810364+46.91638184%2C+-123.99310303+46.91305161%2C+-124.01920319+46.91054916%2C+-124.02610016+46.90832901%2C+-124.03500366+46.90082932%2C+-124.04109955+46.89138031%2C+-124.04139709+46.87887955%2C+-124.03359985+46.877491%2C+-124.03359734+46.87749191%2C+-124.03359222+46.877491%2C+-124.02059937+46.88220978%2C+-124.01139832+46.88137817%2C+-124.01470184+46.87665939%2C+-124.00080109+46.865551%2C+-123.9980011+46.85388184%2C+-124.0019989+46.84915924%2C+-124.01000214+46.84777069%2C+-124.01699829+46.84999847%2C+-124.03079987+46.85971832%2C+-124.03780365+46.86249924%2C+-124.04669952+46.86249161%2C+-124.05280304+46.85971832%2C+-124.0605011+46.86111069%2C+-124.06049347+46.87360001%2C+-124.06919861+46.8810997%2C+-124.0821991+46.8861084%2C+-124.08609772+46.89027023%2C+-124.08688354+46.89583206%2C+-124.08390045+46.90137863%2C+-124.08280182+46.90748978%2C+-124.09670258+46.92554855%2C+-124.10469818+46.91720963%2C+-124.11969757+46.91387939%2C+-124.1207962+46.90776825%2C+-124.11889648+46.90221024%2C+-124.10420227+46.87804031%2C+-124.09941101+46.86693954%2C+-124.09845352+46.86416054%2C+-124.09750366+46.86138153%2C+-124.09750366+46.85832614%2C+-124.09751129+46.85527039%2C+-124.09279633+46.84498978%2C+-124.08969879+46.83304977%2C+-124.084198+46.80276871%2C+-124.08190155+46.75666046%2C+-124.08000183+46.75109863%2C+-124.07330322+46.74277115%2C+-124.06169891+46.73720932%2C+-124.03669739+46.7330513%2C+-124.02749634+46.73360062%2C+-124.01670074+46.73971558%2C+-124.00779724+46.74026871%2C+-124.00080872+46.7383194%2C+-123.9925003+46.73373985%2C+-123.98419952+46.72916031%2C+-123.97109985+46.72415924%2C+-123.96420288+46.72275925%2C+-123.95449829+46.72332001%2C+-123.95220184+46.72887039%2C+-123.95808411+46.73165894%2C+-123.9618988+46.73582077%2C+-123.9618988+46.74222183%2C+-123.95580292+46.74470901%2C+-123.93419647+46.73915863%2C+-123.91846503+46.73675288%2C+-123.91060638+46.73554993%2C+-123.91060313+46.7355506%2C+-123.91059876+46.73554993%2C+-123.89440155+46.73888016%2C+-123.88860321+46.74166107%2C+-123.88639832+46.74637985%2C+-123.8871994+46.75333023%2C+-123.88220215+46.75582886%2C+-123.87220001+46.75582886%2C+-123.86440277+46.75444031%2C+-123.85250092+46.74943924%2C+-123.82499695+46.73416138%2C+-123.81610107+46.727211%2C+-123.80439758+46.71471024%2C+-123.80169678+46.70972061%2C+-123.78309631+46.69527054%2C+-123.76920319+46.69110107%2C+-123.75260162+46.69306946%2C+-123.75330353+46.68888092%2C+-123.75749969+46.68471909%2C+-123.7743988+46.67583084%2C+-123.78330231+46.67527008%2C+-123.7960968+46.68027115%2C+-123.80970001+46.69832993%2C+-123.82639313+46.71416092%2C+-123.83329773+46.71638107%2C+-123.84220123+46.71583557%2C+-123.89420319+46.69749069%2C+-123.90329742+46.689991%2C+-123.90750122+46.67221832%2C+-123.91439819+46.66331863%2C+-123.91670227+46.65776825%2C+-123.91470337+46.65304947%2C+-123.90579987+46.64471054%2C+-123.90420532+46.63916016%2C+-123.90069962+46.63471413%2C+-123.89720154+46.6302681%2C+-123.88169861+46.62026978%2C+-123.88469696+46.61555099%2C+-123.8993988+46.61970901%2C+-123.93778992+46.64083099%2C+-123.93779208+46.64082799%2C+-123.93779755+46.64083099%2C+-123.94080353+46.63665009%2C+-123.92919922+46.62416077%2C+-123.90940094+46.61027908%2C+-123.89219666+46.58055115%2C+-123.88249969+46.56750107%2C+-123.87971497+46.55498886%2C+-123.8828125+46.54333115%2C+-123.88001251+46.53860092%2C+-123.87921906+46.53248596%2C+-123.89891052+46.52555084%2C+-123.91999817+46.51277161%2C+-123.92501831+46.50248337%2C+-123.92420959+46.49694061%2C+-123.92140198+46.49222183%2C+-123.91170502+46.48387909%2C+-123.89201355+46.47664642%2C+-123.88811493+46.47248077%2C+-123.88529968+46.46081924%2C+-123.88220215+46.45666122%2C+-123.8775177+46.45331955%2C+-123.83720398+46.43915939%2C+-123.82831573+46.43165588%2C+-123.82750702+46.42527008%2C+-123.82781219+46.41859818%2C+-123.83170787+46.4144433%2C+-123.86689758+46.43804169%2C+-123.89360046+46.44026947%2C+-123.8993988+46.44305038%2C+-123.90419769+46.45360947%2C+-123.90920258+46.4569397%2C+-123.91221619+46.44527054%2C+-123.9114151+46.43220902%2C+-123.91751862+46.42277145%2C+-123.92970276+46.41109848%2C+-123.93580627+46.39471054%2C+-123.9417038+46.39110947%2C+-123.98719788+46.39305115%2C+-123.98999786+46.39776993%2C+-123.9878006+46.41082001%2C+-123.9905014+46.42860031%2C+-124.01249695+46.48942947%2C+-124.0141983+46.50165939%2C+-124.01499939+46.51470947%2C+-124.01360321+46.54222107%2C+-124.00640106+46.564991%2C+-124.00389862+46.590271%2C+-124.00779724+46.60221863%2C+-124.01080322+46.60694122%2C+-124.03109741+46.62694168%2C+-124.0330958+46.63859641%2C+-124.02999878+46.64360809%2C+-124.01889801+46.64971924%2C+-124.01580048+46.65443039%2C+-124.02089691+46.65803909%2C+-124.02778625+46.65998077%2C+-124.03669739+46.66082001%2C+-124.0428009+46.65803909%2C+-124.04779816+46.64776993%2C+-124.05000305+46.62165833%2C+-124.04109955+46.55887985%2C+-124.03781891+46.52054215%2C+-124.0381012+46.50054932%2C+-124.04139709+46.47581863%2C+-124.03811645+46.42972183%2C+-124.03831482+46.4097023%2C+-124.0406189+46.39665985%2C+-124.03971863+46.39054108%2C+-124.04281616+46.37192917%2C+-124.040802+46.36666107%2C+-124.04111481+46.34666061%2C+-124.04219818+46.33971024%2C+-124.04751587+46.32944107%2C+-124.061409+46.3185997%2C+-124.06250763+46.31248856%2C+-124.05940247+46.30749893%2C+-124.06051636+46.30137634%2C+-124.06970978+46.29333115%2C+-124.07061768+46.28694153%2C+-124.0670166+46.28276825%2C+-124.06000519+46.28081894%2C+-124.06000172+46.2808201%2C+-124.05999756+46.28081894%2C+-124.04000092+46.28749847%2C+-124.01560974+46.28387833%2C+-124.01560952+46.28387943%2C+-124.01560211+46.28387833%2C+-124.01450348+46.28944016%2C+-124.02110291+46.30527115%2C+-124.01920319+46.31082153%2C+-124.01110077+46.31832886%2C+-124+46.3236084%2C+-123.99220276+46.32638931%2C+-123.98331451+46.32638931%2C+-123.96861267+46.32276916%2C+-123.95780182+46.31637573%2C+-123.89940643+46.26776886%2C+-123.87081146+46.26081467%2C+-123.8531189+46.25998306%2C+-123.82231903+46.2727623%2C+-123.82231365+46.27276583%2C+-123.82230377+46.27276993%2C+-123.79140404+46.2930443%2C+-123.78806284+46.29427957%2C+-123.7786026+46.29777145%2C+-123.76860046+46.29777908%2C+-123.75000763+46.28916168%2C+-123.75000212+46.28916266%2C+-123.75+46.28916168%2C+-123.74220276+46.29055023%2C+-123.73719788+46.29388046%2C+-123.73000336+46.30276871%2C+-123.72445711+46.30542522%2C+-123.72421265+46.30554199%2C+-123.70250702+46.29972076%2C+-123.70250134+46.29972129%2C+-123.70249939+46.29972076%2C+-123.69360352+46.30054092%2C+-123.69005731+46.3019993%2C+-123.68750763+46.30304337%2C+-123.68750901+46.30304729%2C+-123.6875+46.303051%2C+-123.69139862+46.31415939%2C+-123.69029999+46.32027054%2C+-123.68609619+46.32444%2C+-123.67720673+46.32500036%2C+-123.67051697+46.32276916%2C+-123.66671753+46.3185997%2C+-123.66000366+46.29610062%2C+-123.65141296+46.28833008%2C+-123.62810516+46.27776337%2C+-123.61221314+46.27499008%2C+-123.58470917+46.27249146%2C+-123.58470383+46.27249166%2C+-123.58470154+46.27249146%2C+-123.55609894+46.27360916%2C+-123.48750305+46.28722%2C+-123.47080231+46.28916168%2C+-123.45201624+46.28971825%2C+-123.42639923+46.28583145%2C+-123.41079712+46.27693176%2C+-123.40701294+46.27192306%2C+-123.40440369+46.26166916%2C+-123.39701843+46.24583054%2C+-123.37670898+46.22637939%2C+-123.36611176+46.21915054%2C+-123.32720184+46.19804001%2C+-123.30280304+46.18082047%2C+-123.2844162+46.17277145%2C+-123.266716+46.1705513%2C+-123.26670808+46.17055222%2C+-123.26670074+46.1705513%2C+-123.25+46.17248917%2C+-123.24176062+46.17489559%2C+-123.23001862+46.17832184%2C+-123.21549414+46.18419025%2C+-123.19220819+46.19359627%2C+-123.16400147+46.1952095%2C+-123.18061829+46.18664169%2C+-123.19059753+46.17916107%2C+-123.19161224+46.17768097%2C+-123.20391083+46.16082001%2C+-123.23390961+46.14749146%2C+-123.24691772+46.14476013%2C+-123.24811554+46.14448929%2C+-123.24970245+46.14416122%2C+-123.2594986+46.1444397%2C+-123.26049805+46.14464951%2C+-123.27420044+46.14749146%2C+-123.29859924+46.15859985%2C+-123.31610107+46.16027069%2C+-123.31611184+46.16027026%2C+-123.31611633+46.16027069%2C+-123.34390694+46.15916105%2C+-123.36049652+46.16082001%2C+-123.39859772+46.17499924%2C+-123.41889954+46.18832016%2C+-123.42669678+46.1972084%2C+-123.42749786+46.20360947%2C+-123.43389893+46.21944046%2C+-123.45639801+46.23138046%2C+-123.46779633+46.24388123%2C+-123.47360229+46.24721909%2C+-123.48829651+46.2508316%2C+-123.48830255+46.25083121%2C+-123.48830414+46.2508316%2C+-123.51420593+46.24916077%2C+-123.51809692+46.24806949%2C+-123.52809906+46.24526978%2C+-123.53527451+46.23965302%2C+-123.56110382+46.21944046%2C+-123.57779694+46.21944046%2C+-123.59059906+46.22526932%2C+-123.59940338+46.22581863%2C+-123.59940583+46.22581783%2C+-123.59941864+46.22581863%2C+-123.60530853+46.22388077%2C+-123.60251617+46.21831512%2C+-123.5858078+46.20943069%2C+-123.58921051+46.20442963%2C+-123.60281372+46.20055008%2C+-123.62940216+46.20027161%2C+-123.69280243+46.18832016%2C+-123.71061679+46.18780234%2C+-123.71170193+46.18777124%2C+-123.72530365+46.19137955%2C+-123.73390198+46.19916153%2C+-123.75029755+46.22248077%2C+-123.75920105+46.22332001%2C+-123.7592023+46.22331941%2C+-123.75920868+46.22332001%2C+-123.78690338+46.20999145%2C+-123.80470276+46.20804977%2C+-123.82440186+46.20804977%2C+-123.83250427+46.2069397%2C+-123.83751678+46.20360947%2C+-123.83830261+46.19860077%2C+-123.83470154+46.19387817%2C+-123.82281494+46.18831253%2C+-123.79920197+46.18471909%2C+-123.77610779+46.16581726%2C+-123.76831818+46.15748978%2C+-123.7664032+46.15193176%2C+-123.77420044+46.15359879%2C+-123.77420532+46.1535982%2C+-123.77420807+46.15359879%2C+-123.78109741+46.152771%2C+-123.7844162+46.14054871%2C+-123.78360021+46.12748903%2C+-123.78469849+46.12137985%2C+-123.80139923+46.1302681%2C+-123.80419922+46.13526917%2C+-123.80079651+46.16054916%2C+-123.8082962+46.17499924%2C+-123.82499695+46.17583084%2C+-123.83810425+46.1705513%2C+-123.84580231+46.16915894%2C+-123.85939789+46.17887878%2C+-123.88500214+46.18943024%2C+-123.90750122+46.20138931%2C+-123.92690277+46.21443939%2C+-123.94139862+46.22637939%2C+-123.94141201+46.22637785%2C+-123.94141388+46.22637939%2C+-123.95830073+46.22443062%2C+-123.9661026+46.22581863%2C+-123.97000122+46.2299881%2C+-123.96690369+46.24166107%2C+-123.9756012+46.24248886%2C+-123.98249817+46.24026871%2C+-123.98281097+46.22803116%2C+-123.9792099+46.21693039%2C+-123.95201111+46.18111038%2C+-123.95111847+46.17554855%2C+-123.93280792+46.14665604%2C+-123.92611694+46.13082123%2C+-123.91691589+46.09553909%2C+-123.91249847+46.07165909%2C+-123.91190338+46.06516266%2C+-123.90921783+46.03387833%2C+-123.90921783+46.02693939%2C+-123.91528309+45.99817473%2C+-123.91560364+45.99665833%2C+-123.92169952+45.98720932%2C+-123.93170929+45.98027039%2C+-123.95829773+45.97166061%2C+-123.96921539+45.96609879%2C+-123.97311401+45.96276855%2C+-123.97531891+45.95666122%2C+-123.95501709+45.92972183%2C+-123.94641113+45.91527176%2C+-123.93699646+45.89471054%2C+-123.93611145+45.88832855%2C+-123.93721008+45.88220978%2C+-123.94611359+45.86804962%2C+-123.94360352+45.83638%2C+-123.94800568+45.81166077%2C+-123.95310974+45.80138016%2C+-123.97311401+45.78165054%2C+-123.9750061+45.77610016%2C+-123.95671844+45.76860046%2C+-123.94779968+45.76166916%2C+-123.92971802+45.73192978%2C+-123.92690277+45.72164917%2C+-123.91750336+45.70027161%2C+-123.91581726+45.68859863%2C+-123.9158058+45.68862467%2C+-123.915802+45.68859863%2C+-123.90859985+45.70499039%2C+-123.89969635+45.71248627%2C+-123.88799818+45.71438506%2C+-123.88420768+45.71499908%2C+-123.88031006+45.71081924%2C+-123.87249756+45.70943069%2C+-123.85670605+45.71221003%2C+-123.86779785+45.69916153%2C+-123.87361145+45.69638062%2C+-123.87569839+45.69624728%2C+-123.89109802+45.69527054%2C+-123.89610291+45.69192886%2C+-123.90029907+45.67470932%2C+-123.92050171+45.64054871%2C+-123.92670441+45.62416077%2C+-123.93060303+45.61249924%2C+-123.93109894+45.59193039%2C+-123.92919922+45.58638%2C+-123.9253006+45.58250046%2C+-123.91361237+45.57749176%2C+-123.89031219+45.57249069%2C+-123.89030475+45.57249237%2C+-123.89029694+45.57249069%2C+-123.87550354+45.57582855%2C+-123.87169647+45.57165909%2C+-123.87781525+45.56221008%2C+-123.88189697+45.55110168%2C+-123.88000488+45.5455513%2C+-123.87609863+45.54138184%2C+-123.87250519+45.53054047%2C+-123.86859894+45.52637863%2C+-123.84220123+45.52415848%2C+-123.83860016+45.51916122%2C+-123.85140991+45.5083313%2C+-123.86330414+45.48915863%2C+-123.86949921+45.48582077%2C+-123.87719727+45.48666%2C+-123.88189697+45.48999023%2C+-123.90309906+45.51639175%2C+-123.92030334+45.52471161%2C+-123.93689728+45.52415848%2C+-123.94390869+45.52082825%2C+-123.9469986+45.51665878%2C+-123.95301056+45.50027084%2C+-123.95500183+45.48720932%2C+-123.95449829+45.47415924%2C+-123.94470215+45.46110916%2C+-123.9178009+45.43832016%2C+-123.91030121+45.42998886%2C+-123.90440369+45.42026901%2C+-123.90470886+45.41360092%2C+-123.90969849+45.40388107%2C+-123.91950226+45.39638901%2C+-123.93330976+45.39499239%2C+-123.93609646+45.39471128%2C+-123.93800354+45.39999008%2C+-123.93080139+45.42277145%2C+-123.93170166+45.42887878%2C+-123.93830109+45.43082047%2C+-123.94529724+45.42193985%2C+-123.94580078+45.39749146%2C+-123.94889832+45.39194107%2C+-123.9539032+45.37471008%2C+-123.96080017+45.36610031%2C+-123.97669983+45.35638046%2C+-123.97779846+45.35026932%2C+-123.97190094+45.3474884%2C+-123.94941711+45.34249115%2C+-123.94580078+45.33832932%2C+-123.93920135+45.32276916%2C+-123.93470001+45.29860687%2C+-123.92610168+45.29111099%2C+-123.92720032+45.28499985%2C+-123.93689728+45.27748871%2C+-123.94580078+45.26305008%2C+-123.95310211+45.24055099%2C+-123.95337066+45.23903386%2C+-123.95640564+45.22193146%2C+-123.95560455+45.20915985%2C+-123.94329834+45.18360138%2C+-123.94249725+45.17749023%2C+-123.94439697+45.16444016%2C+-123.96060181+45.13582993%2C+-123.96250916+45.12971115%2C+-123.97399835+45.1102726%2C+-123.98549652+45.09083176%2C+-123.99359894+45.06137848%2C+-123.99220276+45.02165985%2C+-123.99449921+45.00944138%2C+-123.99500275+44.97776031%2C+-124.00309753+44.94916153%2C+-123.99469757+44.92026901%2C+-123.99780273+44.91693878%2C+-124.0044966+44.91499085%2C+-124.01029968+44.91777039%2C+-124.01419067+44.92193985%2C+-124.01419275+44.92193392%2C+-124.0141983+44.92193985%2C+-124.01809692+44.91082001%2C+-124.02249908+44.88694%2C+-124.02950287+44.87054062%2C+-124.03829956+44.85694122%2C+-124.05390167+44.83998871%2C+-124.05580139+44.83388138%2C+-124.05419922+44.82888031%2C+-124.0503006+44.82416916%2C+-124.05049896+44.81055069%2C+-124.0535965+44.80027008%2C+-124.05940247+44.78999329%2C+-124.05940136+44.78999143%2C+-124.05940247+44.78998947%2C+-124.05079651+44.77555084%2C+-124.05110168+44.76388931%2C+-124.0428009+44.74805069%2C+-124.03919983+44.73027039%2C+-124.04720306+44.70859909%2C+-124.04799652+44.70222092%2C+-124.05500031+44.6935997%2C+-124.05609894+44.68721008%2C+-124.0428009+44.67638016%2C+-124.040802+44.67082977%2C+-124.04309845+44.65166092%2C+-124.04109955+44.64609909%2C+-124.03749847+44

In [62]:
## TODO try getting the bounding box geometry instead since the full region geom is HUGE